# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7ee31d19496faff2b51dd1232370fd3a4951a0e48e5d67dbdd2284d7472281349dc9eb6d91e74c4c42cfc54fe3beaf4b6c056f9e1a8d7c117cf0996d709c343

test:
  secret_key_base: 9767dc98287a27afca8e3b387678279cc77d7dde8bad8446840e1d24d90c3054f5b2b194336ce839796a6ad71f8874173e7311493c4f47b83e292a3c8b007a02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
